---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: ingress-nginx
  namespace: cluster-config
spec:
  interval: 1m0s
  url: https://kubernetes.github.io/ingress-nginx

